language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:
# - npm install -g gulp


script:
  - hexo clean && hexo algolia && hexo g
  - cd ./public
  - git init
  - git config user.name "imxushuai"
  - git config user.email "imxushuai@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - git push --force --quiet "https://imxushuai:${CO_TOKEN}@${CO_REF}" master:master



branches:
  only:
    - hexo
env:
  global:
    - GH_REF: github.com/imxushuai/imxushuai.github.io.git
    - CO_REF: git.dev.tencent.com/imxushuai/imxushuai.coding.me.git
